apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goo
  janus-idp.io/tekton: goo
  backstage.io/kubernetes-id: goo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goo
resources:
- deployment.yaml
- route.yaml
- service.yaml
