apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goo 
  name: goo
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goo 
